version: "3.9"

services:
  front-service:
    image: dendriel/config-creator-front
    ports:
      - 80:80
    restart: always
    volumes:
      - /e/workspace/config-creator/conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  rest-service:
    image: dendriel/config-creator-rest
    restart: always
    ports:
      - 8081:8081
    environment:
      - MONGO_DB_HOST=host.docker.internal
      - AUTH_SERVICE_URL=http://auth-service:8080
      - EXPORTER_QUEUE_URL=http://sqs-service:9324
      - AWS_ACCESS_KEY_ID=1111
      - AWS_SECRET_KEY=2222
  auth-service:
    image: dendriel/npc-data-manager-auth:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      - MYSQL_DB=the_quest
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=3306
      - MYSQL_USER=docker
      - MYSQL_PASS=pass
  storage-service:
    image: dendriel/npc-data-manager-storage:latest
    restart: always
    ports:
      - 8082:8082
    volumes:
      - c:\.aws:/root/.aws:ro
    environment:
      - MYSQL_DB=the_quest
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=3306
      - MYSQL_USER=docker
      - MYSQL_PASS=pass
      - AUTH_URL=http://auth-service:8080
  exporter-service:
    image: dendriel/config-creator-exporter
    restart: always
    environment:
      - SERVICE_URL=http://front-service
      - QUEUE_URL=http://sqs-service:9324/queue/export-request
      - AUTH_KEY=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleHBvcnRlciIsImV4cCI6MTYzMTc1MDE4NCwiaWF0IjoxNjI5MTU4MTg0fQ.45AW5A7mp7gGCdYztoAadzPPumdV7MAiAXGpBX4be_8
  sqs-service:
    image: roribio16/alpine-sqs:latest
    restart: always
    ports:
      - 9324:9324
      - 9325:9325
    volumes:
      - /e/workspace/config-creator/conf/sqs:/opt/custom

# mongodb
# mysql
